In [16]:
#User input array
import numpy as np
a=[]
n=int(input("Enter the size of arr"))
for i in range(n):
    val=int(input("Enter no"))
    a.append(val)
myarr=np.array(a)
myarr


Enter the size of arr 5
Enter no 1
Enter no 2
Enter no 3
Enter no 4
Enter no 5


array([1, 2, 3, 4, 5])

In [14]:
#Predefined array
import numpy as np

x=np.array([1,2,3])#1D array
y=np.array([[1,2,3],[4,5,6]])#2D array
z=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])#3D array

print(x)
print(y)
print(z)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
